services:
  _defaults:
    autowire: true
    autoconfigure: true

  ICS\MediaBundle\Controller\:
    resource: "../../Controller"
    tags: ['controller.service_arguments']
  ICS\MediaBundle\Service\:
    resource: "../../Service"
    tags: ['controller.service_arguments']
  ICS\MediaBundle\Command\:
    resource: "../../Command"
    tags: ['controller.service_arguments']
  ICS\MediaBundle\Twig\:
    resource: "../../Twig"
    public: false
    tags: ['twig.extension']
  ICS\MediaBundle\Form\:
    resource: "../../Form"
    public: false
    tags: ['controller.service_arguments']
