services:
  _defaults:
    autowire: true
    autoconfigure: true

  ICS\MediaBundle\Controller\:
    resource: "../../Controller"
    public: true
    tags: ['controller.service_arguments']
  ICS\MediaBundle\Service\:
    resource: "../../Service"
    public: true
    tags: ['controller.service_arguments']
  ICS\MediaBundle\Command\:
    resource: "../../Command"
    tags: ['controller.service_arguments']
  ICS\MediaBundle\Twig\:
    resource: "../../Twig"
    public: true
    tags: ['twig.extension']
  ICS\MediaBundle\Form\:
    resource: "../../Form"
    public: true
    tags: ['controller.service_arguments']
  ICS\MediaBundle\Service\MediaClient:
        # redundant thanks to _defaults, but value is overridable on each service
        autowire: true
